### ISSUE TITLE
UT-zap50k

### ISSUE THREAD

**Issue by nanzhixionggit** [Tushar-N/attributes-as-operators#3]
Hi, I download the UT-zap50k dataset according to your link. I find 83 training pairs. but, i can not find the images for certain pair. For example,  the first pair is ''Canvas Boots_Ankle'', I can find the folder ../images/Boots/, but I can not find images with attribute Canvas under this folder.  Can you tell me what is wrong?

**Comment by Tushar-N** [comment]
Hi, the UT-zap data subset isn't organized (physically) the same way as the MIT-States data. The original data was organized by coarse class labels, and not by attributes. The attribute information is in the metadata file `data/ut-zap50k/metadata.pkl`, which is read and parsed in the dataset class [here](https://github.com/Tushar-N/attributes-as-operators/blob/master/dataset.py#L264).

Let me know if this is enough information, or I can write a script to make symlinks to replicate the MIT-States folder structure (it'll be a while before I get to it though).

**Comment by nanzhixionggit** [comment]
thank you very much, I will try it today! If I solved, I will let you know!

**Comment by nanzhixionggit** [comment]
Hi, it works. thank you very much.  only two little issues: 1. Boots/Mid-Calf/Pablosky Kids/8029595.574.jpg does not exist
2.  training image number is 24897 and test image number 4227,  is this right?

**Comment by Tushar-N** [comment]
Hi, 
1. You're right! I'm not sure how that happened. Thanks for pointing that out, I'll correct it soon.
2. Yes, this sounds about right.
